
#数据源相关设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.255.129:3306/blog
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#MyBatis相关设置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.atguigu.blog.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#给Tomcat服务器设置自定义端口号，默认为8080
server:
  port: 8001
